[package]
name = "win95-keygen-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.1"
clap = { version = "4.4", features = ["derive"] } 
rayon = "1.8"
